### PR TITLE
Added support for pull requests on Buildkite

### PR DESCRIPTION
**Pull request by keithpitt**
Hey! I hope this PR is OK! I added support for Buildkite in the list of CI providers that danger works with.

Let me know if it's missing anything! :dancers:

### CODE REVIEW

**Comment by keithpitt** [comment]
Ah, looks like @houndci isn't happy. I copied an existing CI provider and changed it for Buildkite. Do you want me to go through what hound wants me to change and change it? Also, I noticed the build failed, but I can't seem to figure out why! The specs seem to pass!

**Comment by KrauseFx** [comment]
@keithpitt I think @houndci is drunk and confused, I'm going to disable it for this repo for now. Thank you for your pull request, reviewing now :+1:

**Comment by KrauseFx** [comment]
Looks great, thank you so much @keithpitt :+1:

**Comment by orta** [comment]
Woooooooo

**Comment by keithpitt** [comment]
Heh, yeah, it did go a little drunk :) Thanks so much for merging the PR! :dancers:

**Comment by mokagio** [comment]
:tada:

**Pull request merged**
