### PR TITLE
Added 'danger willrobinson' easter egg

### PR DESCRIPTION
**Pull request by samritchie**
Every command line tool needs an easter egg with breathtaking ASCII art.

### CODE REVIEW

**Comment by orta** [comment]
Interestingly enough, the motto of house Danger is: everything is fixable.

**Comment by samritchie** [comment]
Wait, is that REALLY orta?

**Comment by orta** [comment]
heh, yep. This project is named after my girlfriend, Danger. That's her house motto. Mine is; Time and Patience.

**Comment by KrauseFx** [comment]
I'm confused :confused:

**Comment by orta** [comment]
haha

**Comment by orta** [comment]
Giphy

**Comment by orta** [comment]
we should ship this? Either that or we ship an ASCII version of [my girlfriend](https://www.facebook.com/gem.mcshane/) ;)

**Comment by KrauseFx** [comment]
Hi there o/

**Comment by KrauseFx** [comment]
[danger warning] Hi there o/

**Comment by KrauseFx** [comment]
danger ⚠️ HPull Request exceeds maximum number of changed lines

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
------------- | ------------

  :no_entry_sign: | Orta is not really orta


&nbsp; | 1 Warnings
------------- | ------------

  :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
------------- | ------------ Orta is not really orta


&nbsp; | 1 Warnings
------------- | ------------ Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
------------- | ------------ 
  :no_entry_sign: | Orta is not really orta


&nbsp; | 1 Warnings
------------- | ------------ 
  :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta
  



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning
  


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 2 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta
  
    :no_entry_sign: | Some random warning
  



  :white_check_mark: No warnings found


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 2 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta
    :no_entry_sign: | Some random warning



  :white_check_mark: No warnings found


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
:white_check_mark: No errors found



  :white_check_mark: No warnings found


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by samritchie** [comment]
Awesome, orta is now orta. The universe breathes a sigh of relief.

**Comment by KrauseFx** [comment]
Fixed @orta

**Comment by KrauseFx** [comment]
:white_check_mark: No errors found



  :white_check_mark: No warnings found


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning



  &nbsp; | 1 Messages
  ------------- | ------------ 
    :book: | This pull request adds 0 new lines


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 1 Warnings
  ------------- | ------------ 
    :warning: | Some random warning



  &nbsp; | 1 Messages
  ------------- | ------------ 
    :book: | This pull request adds 0 new lines


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 2 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta
    :no_entry_sign: | Unkown author 



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | Some random warning



  &nbsp; | 1 Message
  ------------- | ------------ 
    :book: | This pull request adds 0 new lines


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 2 Errors
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta
    :no_entry_sign: | Unkown author samritchie



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | Some random warning



  &nbsp; | 1 Message
  ------------- | ------------ 
    :book: | This pull request adds 0 new lines


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 2 Warnings
  ------------- | ------------ 
    :warning: | Some random warning
    :warning: | Author @samritchie is not a contributor



  &nbsp; | 1 Message
  ------------- | ------------ 
    :book: | This pull request adds 0 new lines


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | Orta is not really orta



  &nbsp; | 2 Warnings
  ------------- | ------------ 
    :warning: | Some random warning
    :warning: | Author @samritchie is not a contributor



  &nbsp; | 2 Messages
  ------------- | ------------ 
    :book: | This pull request adds 0 new lines
    :book: | #<Sawyer::Resource:0x007f92ccbab4c0>


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
:white_check_mark: No errors found



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | Author @samritchie is not a contributor



  &nbsp; | 1 Message
  ------------- | ------------ 
    :book: | Tests are updated / added


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
:white_check_mark: No errors found



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | Author @samritchie is not a contributor



  &nbsp; | 1 Message
  ------------- | ------------ 
    :book: | Tests are updated / added


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by KrauseFx** [comment]
:white_check_mark: No errors found



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | Author @samritchie is not a contributor



  &nbsp; | 1 Message
  ------------- | ------------ 
    :book: | Tests are updated / added


<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-04</i>
</p>

**Comment by orta** [comment]
Alright, I'm calling this ( especially as it's now full of felix-bot comments :D ) and closing it, I like the idea, but not yet, easter eggs can come post-1.0

**Pull request closed without merging**
