### PR TITLE
@orta => use a Dangerfile on this repo

### PR DESCRIPTION
**Pull request by orta**
I'm not really Orta

### CODE REVIEW

**Comment by KrauseFx** [comment]
@orta hacking on `danger` again? :+1: I haven't yet merged to master, all changes are on this branch.

**Comment by orta** [comment]
Yeah, I started taking a look on this branch, no worries :+1:

**Comment by KrauseFx** [comment]
Yeah, great work @orta. How about we merge to master and then work with pull requests again, so that we can easily review each others code?

**Comment by orta** [comment]
@KrauseFx when I tried to get rubocop to run locally I couldn't get it to replicate hound's errors, any chance you can set that up?

**Comment by orta** [comment]
yeah, merge is good.

**Comment by KrauseFx** [comment]
@orta I think it's just a caching error of hound, because it's not in the main branch yet.

**Pull request merged**
